version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34.8
    restart: always
    ports:
    - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            uri: "postgres://postgres:postgres@postgres:5432/postgres"
            migrations: true
            rawAccess: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  nats:
    image: nats
    restart: always
    command: "-c nats-server.conf --routes=nats-route://ruser:T0pS3cr3t@nats:6222"
    ports:
    - 4222:4222
    - 6222:6222
    - 8222:8222
  nats-2:
    image: nats
    restart: always
    command: "-c nats-server.conf --routes=nats-route://ruser:T0pS3cr3t@nats:6222"
    ports:
    - 4222
    - 6222
    - 8222
  nats-streaming:
    image: nats-streaming:0.17.0
    restart: always
    command: "-DV -m 8222 --cluster_id houston"
volumes:
  postgres:
