# API webserver configuration.
webserver:
  port: 8871
  endpoint: "/v1"
  subscriptions: "/ws"

# Commander configuration.
commander:
  enabled: false

# Charts live here.
# This is where the airflow chart is installed from.
repository: "https://helm.astronomer.io/"

# Test that we can disable a specific permission in an override
roles:
  SYSTEM_VIEWER:
    permissions:
      system.monitoring.get: false

# Helm configuration.
# These values are set at runtime and used for airflow deployments.
helm:
  baseDomain: astronomer.io
  acme: ~
  rbacEnabled: ~
  releaseName: astronomer
  releaseNamespace: astronomer
  # need for testing src/resolvers/query/platform-releases/index.unit.test.js:41
  releaseVersion: 0.0.1

# Auth configuration.
auth:
  # Local database (user/pass) configuration.
  local:
    enabled: true

  openidConnect:
    # Auth0 integration configuration.
    auth0:
      # This "enabled" flag is currently a little misleading.
      # The enabled flag refers only to showing the native
      # Auth0 button in the UI. The rest of the settings here
      # could potentially be used as to auth with Google/Github/etc
      # if those integrations are enabled, but do not have connection
      # information.
      enabled: true
      clientId: ~
      discoveryUrl: https://astronomerio.auth0.com
      authUrlParams:
        audience: "astronomer-ee"

    # Direct oauth integration to google.
    google:
      displayName: Google
      enabled: true
      clientId: ~
      discoveryUrl: "https://accounts.google.com/"

  # Direct oauth integration to github (WIP).
  github:
    enabled: false

# Passphrase to sign JWTs with.
jwt:
  passphrase: "abcdefg"

  # JWT / Cookie duration in milliseconds.
  authDuration: 86400000
  certPath: ./test-data/certs/
  registry:
    certPath: ./test-data/certs/

# Deployment configuration.
deployments:
  chart:
    version: 1.2.3

  database:
    enabled: false

  images:
    - version: 1.10.4
      channel: stable
      tag: 1.10.4-alpine3.10-onbuild
    - version: 1.10.5
      channel: stable
      tag: 1.10.5-alpine3.10-onbuild
    - version: 1.10.6
      channel: edge
      tag: 1.10.6-alpine3.10-onbuild

# Stripe configuration.
stripe:
  enabled: true
